language: java
jdk: openjdk10
cache:
  directories:
  - $HOME/.m2
services:
  - postgresql
env:
  global:
    - DATABASE_TEST_JDBC=jdbc:postgresql://127.0.0.1:5432/gatekeeper
    - DATABASE_TEST_USER=postgres
    - DATABASE_TEST_PASSWORD=''
before_script:
  - psql -c 'CREATE DATABASE gatekeeper;' -U postgres

script:
  - mvn clean install
  - java -jar target/gatekeeper-0.1.0-SNAPSHOT.jar check config-DANGEROUS-AND-INSECURE.yml

notifications:
  email: false
