language: java
jdk: openjdk11
sudo: required
cache:
  directories:
  - $HOME/.m2
services:
  - postgresql
  - docker
addons:
  apt:
    packages:
      - docker-ce
env:
  global:
    - DATABASE_JDBC=jdbc:postgresql://127.0.0.1:5432/gatekeeper
    - DATABASE_TEST_JDBC=jdbc:postgresql://127.0.0.1:5432/gatekeeper
    - DATABASE_TEST_USER=postgres
    - DATABASE_TEST_PASSWORD=''
    - DATABASE_URL=postgres://postgres@127.0.0.1:5432/gatekeeper?sslmode=disable
before_script:
  - psql -c 'CREATE DATABASE gatekeeper;' -U postgres
  - mvn clean install -DskipTests
  - java -jar target/gatekeeper-0.1.0-SNAPSHOT.jar db migrate config.yml

script:
  - ./mvnw clean install
  - java -jar target/gatekeeper-0.1.0-SNAPSHOT.jar check config.yml

after_success:
  - bin/docker-push.sh

notifications:
  email: false
