language: java
jdk: openjdk11
sudo: required
cache:
  directories:
  - $HOME/.m2
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce

script:
  - ./mvnw clean install

after_success:
  - bin/docker-push.sh

notifications:
  email: false
