refreshTokenExpirationTimeInDays: 365
accessTokenExpirationTimeInSeconds: 1800 # 30 minutes
allowedHostedDomains: ["hedvig.com"]

allowedRedirectDomains: ["hedvig.com", "hedviglocaldev.com", "dev.hedvigit.com"]
secureCookies: ${SECURE_COOKIES:-false}
cookieDomain: ${COOKIE_DOMAIN:-hedviglocaldev.com}
selfHost: ${SELF_HOST:-http://hedviglocaldev.com:8040}

logging:
  level: INFO

server:
  type: default
  applicationConnectors:
    - type: http
      port: ${PORT:-8040}
  adminConnectors:
    - type: http
      port: ${ADMIN_PORT:-8041}

database:
  driverClass: org.postgresql.Driver
  url: ${DATABASE_JDBC}
  user: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  properties:
    charSet: UTF-8

  maxWaitForConnection: 5s

  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s

  minSize: 2
  maxSize: 32

  checkConnectionWhileIdle: false
  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

secrets:
  jwtSecret: ${JWT_SECRET}
  googleClientId: ${GOOGLE_CLIENT_ID}
  googleClientSecret: ${GOOGLE_CLIENT_SECRET}
  googleWebClientId: ${GOOGLE_WEB_CLIENT_ID}
  selfOauth2ClientId: ${SELF_OAUTH2_CLIENT_ID}
  selfOauth2ClientSecret: ${SELF_OAUTH2_CLIENT_SECRET}

