logging:
  level: INFO
  loggers:
    com.hedvig: ${LOG_LEVEL:-DEBUG}
  appenders:
    - type: console
      threshold: ALL
      queueSize: 512
      discardingThreshold: 0
      timeZone: UTC
      target: stdout
      logFormat: "%-5p [%d{ISO8601,UTC}] [request_id=%X{Request-Tracker}] %c{5}: %m%n%rEx"

server:
  type: default
  applicationConnectors:
  - type: http
    port: ${PORT:-8334}
  adminConnectors:
  - type: http
    port: ${ADMIN_PORT:-8335}

auth:
  grantTypes: []

database:
  driverClass: org.postgresql.Driver
  url: ${DATABASE_JDBC:-dotenv}
  user: ${DATABASE_USER:-dotenv}
  password: ${DATABASE_PASSWORD:-dotenv}
  properties:
    charSet: UTF-8

  maxWaitForConnection: 5s

  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s

  minSize: 2
  maxSize: 32

  checkConnectionWhileIdle: false
  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute
